sql_server:
 connection_parameters:
  'db_driver': '{SQL Server}' 
  'db_server': 'localhost' # адрес SQL сервера
  'db_name': 'test_task' # имя рабочей БД
 default_parameters:
  schema: ch # название схемы по умолчанию
  import_data_table: raw_data # имя таблицы с данными
  raw_data_procedure: get_raw_data # имя процедуры выгрузки сырых данных по умолчанию
  report_data_procedure: get_report_data # имя процедуры выгрузки отчета по умолчанию